### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by jrings** [GGiecold/DBSCAN_multiplex#2]
Trying to run the setup, I get

```
  File "setup.py", line 20
SyntaxError: Non-ASCII character '\xe2' in file setup.py on line 21, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

This should be fixable by adding

``` python
# -*- coding: utf-8 -*-
```

to the top of the file. Same for the DBSCAN_multiplex.py.

I'll draft a quick PR!

**Comment by GGiecold-zz** [comment]
Thank you for pointing this out. Your pull request has been merged onto
DBSCAN_multiplex's Git repository

With kind regards,

Gregory

**Comment by jrings** [comment]
Thanks :)
