### ISSUE TITLE
Warning! ***HDF5 library version mismatched error***

### ISSUE THREAD

**Issue by Brick-Mover** [GGiecold/DBSCAN_multiplex#7]
Here is the error message:

The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.8.17, library is 1.8.18

**Comment by GGiecold-zz** [comment]
This issue pertains to the HDF5 library on your machine, not to
DBSCAN_multiplex.

Gregory
